configfile: "config/config.yaml"

ASSAY = config["project"]["assay"]
include: "workflow/rules/common.smk"

if ASSAY == "wgbs":
    include: "workflow/rules/wgbs.smk"
elif ASSAY == "snrna":
    include: "workflow/rules/snrna.smk"
elif ASSAY == "wgs":
    include: "workflow/rules/wgs.smk"
else:
    raise ValueError(f"Unknown assay: {ASSAY}. Must be one of: wgbs, snrna, wgs")

rule all:
    input:
        f"{config['paths']['outdir']}/{ASSAY}/_SUCCESS"
