executor: slurm
jobs: 100
latency-wait: 60
rerun-incomplete: true
keep-going: true
printshellcmds: true

default-resources:
  - threads=4
  - mem_mb=16000
  - time_min=240
  - partition=production
  - qos=normal

slurm:
  extra: "--parsable"
  time: "{resources.time_min}"
  mem_mb: "{resources.mem_mb}"
  partition: "{resources.partition}"
  qos: "{resources.qos}"
  cpus-per-task: "{threads}"
